/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.helloworld;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int api_key_input=0x7f040004;
        public static final int boot_toggle=0x7f040006;
        public static final int count_text=0x7f040002;
        public static final int restart_button=0x7f040007;
        public static final int server_host_input=0x7f040003;
        public static final int service_toggle=0x7f040005;
        public static final int status_text=0x7f040001;
        public static final int subtitle=0x7f040000;
        public static final int sync_button=0x7f040008;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
